import { Inter } from "next/font/google";
import "./globals.css";
import Appbar1 from "@/components/Appbar1";
import Appbar2 from "@/components/Appbar2";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Online Judge",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Appbar1 />
        <Appbar2 />
        {children}
        <Footer />
      </body>
    </html>
  );
}
