import { Inter } from "next/font/google";
import "./globals.css";
import Appbar1 from "@/components/Appbar1";
import Appbar2 from "@/components/Appbar2";
import Footer from "@/components/Footer";
import { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Online Judge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Appbar1 />
        <Appbar2 />
        <div className="mt-24">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
